spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/spendings
    username: postgres
    password: mysecretpassword
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
